#!/bin/bash

export MOLECULE_IMAGE="quay.io/samdoran/fedora32-ansible"
export MOLECULE_DISTRIBUTION="fedora32"
export MOLECULE_SCENARIO="default"
# https://github.com/ansible/ansible/issues/67004
export ANSIBLE_PIPELINING=false
