#!/bin/bash

export MOLECULE_IMAGE="quay.io/samdoran/ubuntu20-ansible"
export MOLECULE_DISTRIBUTION="ubuntu20"
export MOLECULE_SCENARIO="default"
# https://github.com/ansible/ansible/issues/67004
export ANSIBLE_PIPELINING=false
